### ISSUE TITLE
Cannot set property 'existsSync' of undefined

### ISSUE THREAD

**Issue by bermudalocket** [carson-katri/swiftwebui-scripts#1]
- OS: `Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-99-generic x86_64)`
- node: `8.10.0`
- npm: `3.5.2`
- npx: `10.2.2`
- swift: `Swift version 5.2.3 (swift-5.2.3-RELEASE)`

Reproduce:
1. `apt install npm`
2. `npm i -g npx`
3. `npx carson-katri/swiftwebui-scripts create MyApp`

Output from step 3:
```
npx: installed 11 in 3.408s
Cannot set property 'existsSync' of undefined
```

Per instructions, expected a project directory to be created at the same path but none is created. Running the same `npx` command again produces the exact same output.

**Comment by carson-katri** [comment]
I believe the issue lies with your Node version. Try updating to node 10 or later and run the command again. `fs/promises` was added in v10.

**Comment by bermudalocket** [comment]
Working beautifully now. Thank you!
