### ISSUE TITLE
wasm-strip: command not found

### ISSUE THREAD

**Issue by shial4** [carson-katri/swiftwebui-scripts#2]
when I run make I do get 
```
wasm-strip: command not found
```

How do I install it? with what package does it come?

**Comment by carson-katri** [comment]
It is a part of [wabt](https://github.com/WebAssembly/wabt), you can install with brew:
`brew install wabt`

I'll add a check so the tool logs something more useful.

**Comment by carson-katri** [comment]
There is now a more useful error message, and a flag for creating an app without optimizations: https://github.com/carson-katri/swiftwebui-scripts/commit/c19e8719901d0098d1e40db74d2d970da2315eeb

**Comment by shial4** [comment]
> It is a part of [wabt](https://github.com/WebAssembly/wabt), you can install with brew:
> `brew install wabt`
> 
> I'll add a check so the tool logs something more useful.

Thanks, wasn't sure which pack to install to have it. There is so many of them.
